import { IGameConfig, IThemeConfig, ILocales } from './types/ConfigTypes';
// @ts-ignore
import UserConfig from './UserConfig.json';

// --- 1. LOCALIZATION ---
export const Locales: ILocales = {
    en: {
        startBtn: "START",
        jumpBtn: "JUMP",
        winTitle: "BIG WIN",
        winCta: "PLAY NOW!",
        balanceLabel: "Balance",
        multiplierLabel: "Multiplier"
    },
    ru: {
        startBtn: "ИГРАТЬ",
        jumpBtn: "ПРЫГОК",
        winTitle: "ПОБЕДА",
        winCta: "ЗАБРАТЬ!",
        balanceLabel: "Баланс",
        multiplierLabel: "Множитель"
    },
    pt: {
        startBtn: "JOGAR",
        jumpBtn: "PULAR",
        winTitle: "GRANDE VITÓRIA",
        winCta: "JOGUE AGORA!",
        balanceLabel: "Saldo",
        multiplierLabel: "Multiplicador"
    },
    es: {
        startBtn: "JUGAR",
        jumpBtn: "SALTAR",
        winTitle: "GRAN VICTORIA",
        winCta: "¡JUEGA AHORA!",
        balanceLabel: "Saldo",
        multiplierLabel: "Multiplicador"
    }
};

// --- 2. THEME REGISTRY ---
export const Themes: Record<string, IThemeConfig> = {
    'chicken_farm': {
        id: 'chicken_farm',
        name: 'Classic Chicken',
        colors: {
            background: 0x87ceeb,
            uiPrimary: '#22c55e',
            uiSecondary: '#ef4444',
            text: '#ffffff'
        },
        assets: {
            images: {
                ground: './assets/ground_tile.webp',
                track: './assets/railroad.webp',
                platform: './assets/platform.webp',
                player_idle: './assets/idle.gif',
                player_jump: './assets/idle.gif',
                player_crash: './assets/death.gif',
                obstacle: './assets/train.webp',
                coin: './assets/coin_small.webp',
                win_bg: './assets/scroll_body.webp'
            },
            audio: {
                bgm: './assets/audio/main_theme.ogg',
                jump: './assets/audio/move.ogg',
                crash: './assets/audio/pn.ogg',
                win: './assets/audio/big_win.ogg'
            }
        }
    },
    'cyber_city': {
        id: 'cyber_city',
        name: 'Cyberpunk Run',
        colors: {
            background: 0x0f0f1a,
            uiPrimary: '#00ffcc',
            uiSecondary: '#ff0099',
            text: '#ccff00'
        },
        assets: {
            images: {
                // Placeholder paths - user needs to provide these or we use fallbacks
                ground: './assets/cyber/ground.webp',
                track: './assets/cyber/rail.webp',
                platform: './assets/cyber/platform.webp',
                player_idle: './assets/cyber/robot_idle.png',
                player_jump: './assets/cyber/robot_jump.png',
                player_crash: './assets/cyber/explosion.png',
                obstacle: './assets/cyber/car.webp',
                coin: './assets/cyber/chip.webp',
                win_bg: './assets/cyber/holo_panel.webp'
            },
            audio: {
                bgm: './assets/audio/cyber_theme.ogg',
                jump: './assets/audio/laser_jump.ogg',
                crash: './assets/audio/glitch.ogg',
                win: './assets/audio/cyber_win.ogg'
            }
        }
    }
};

// --- 3. CURRENT CONFIG ---
// THIS IS GENERATED BY THE BOT (via UserConfig.json)
export const GameConfig: IGameConfig = {
    user: UserConfig,
    
    core: {
        maxSteps: 8,
        verticalCenter: 0.6,
        cameraZoom: {
            portrait: 0.70,
            landscape: 0.8
        },
        trackSpacing: 240
    }
};

export const getCurrentTheme = () => Themes[GameConfig.user.themeId] || Themes['chicken_farm'];
export const getCurrentLocale = () => Locales[GameConfig.user.language] || Locales['en'];